apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: my-usr-vol
  name: my-usr-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
